# Generated by Django 5.0.1 on 2026-01-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_salida_normalizada"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="planificacionnormalizada",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="salidanormalizada",
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name="planificacion",
            index=models.Index(
                fields=["normalize_status", "plan_month"],
                name="main_planif_normali_166e45_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="planificacion",
            index=models.Index(
                fields=["item_code"], name="main_planif_item_co_4c5fee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="planificacion",
            index=models.Index(
                fields=["sucursal"], name="main_planif_sucursa_9b499b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="planificacion",
            index=models.Index(
                fields=["plan_month", "item_code", "sucursal"],
                name="main_planif_plan_mo_c425c6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="planificacionnormalizada",
            index=models.Index(
                fields=["plan_month", "item_code"],
                name="main_planif_plan_mo_cec524_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="planificacionnormalizada",
            index=models.Index(
                fields=["plan_month", "sucursal"], name="main_planif_plan_mo_b94fbc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salida",
            index=models.Index(
                fields=["normalize_status", "fecha_salida"],
                name="main_salida_normali_1b3108_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="salida",
            index=models.Index(fields=["sku"], name="main_salida_sku_98bd71_idx"),
        ),
        migrations.AddIndex(
            model_name="salida",
            index=models.Index(
                fields=["nombre_sucursal_origen"], name="main_salida_nombre__2a2479_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salida",
            index=models.Index(
                fields=["nombre_sucursal_destino"],
                name="main_salida_nombre__8990da_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="salidanormalizada",
            index=models.Index(
                fields=["fecha_salida", "sku"], name="main_salida_fecha_s_d4e72f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salidanormalizada",
            index=models.Index(
                fields=["fecha_salida", "sucursal_origen"],
                name="main_salida_fecha_s_b4c84a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="salidanormalizada",
            index=models.Index(
                fields=["fecha_salida", "sucursal_destino"],
                name="main_salida_fecha_s_60556c_idx",
            ),
        ),
    ]
