# Generated by Django 5.0.1 on 2026-01-14 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_alter_planificacionnormalizada_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="planificacionnormalizada",
            name="sucursal_origen",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="planificaciones_origen",
                to="main.sucursal",
            ),
        ),
        migrations.AlterField(
            model_name="planificacion",
            name="normalize_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendiente"),
                    ("ok", "Normalizado"),
                    ("error", "Error"),
                    ("ignored", "Ignorado"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="planificacionnormalizada",
            name="sucursal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="planificaciones_destino",
                to="main.sucursal",
            ),
        ),
    ]
