# Generated by Django 5.0.1 on 2026-01-14 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_add_sucursal_origen_to_planificacion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="planificacionnormalizada",
            name="sucursal_origen",
        ),
        migrations.AddField(
            model_name="planificacionnormalizada",
            name="cedis_origen",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="planificaciones_origen",
                to="main.cendis",
            ),
        ),
    ]
