# Generated by Django 5.0.1 on 2026-01-14 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_change_sucursal_origen_to_cedis_origen"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cendis",
            options={
                "ordering": ["code"],
                "verbose_name": "CEDIS (Almacén)",
                "verbose_name_plural": "CEDIS (Almacenes)",
            },
        ),
        migrations.RemoveIndex(
            model_name="salidanormalizada",
            name="main_salida_fecha_s_b4c84a_idx",
        ),
        migrations.RemoveField(
            model_name="salidanormalizada",
            name="sucursal_origen",
        ),
        migrations.AddField(
            model_name="salidanormalizada",
            name="cedis_origen",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="salidas_origen",
                to="main.cendis",
            ),
        ),
        migrations.AddIndex(
            model_name="salidanormalizada",
            index=models.Index(
                fields=["fecha_salida", "cedis_origen"],
                name="main_salida_fecha_s_755727_idx",
            ),
        ),
    ]
