# Generated by Django 6.0.1 on 2026-01-16 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_update_salida_normalizada_origen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sucursal',
            options={'ordering': ['name'], 'verbose_name': 'Sucursal (Tienda)', 'verbose_name_plural': 'Sucursales (Tiendas)'},
        ),
        migrations.AlterField(
            model_name='cendis',
            name='code',
            field=models.CharField(help_text='Código único del CEDIS', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='cendis',
            name='origin',
            field=models.CharField(help_text='Nombre del almacén/centro de distribución', max_length=255),
        ),
        migrations.AlterField(
            model_name='planificacionnormalizada',
            name='cedis_origen',
            field=models.ForeignKey(blank=True, help_text='Almacén origen', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planificaciones_origen', to='main.cendis'),
        ),
        migrations.AlterField(
            model_name='planificacionnormalizada',
            name='sucursal',
            field=models.ForeignKey(help_text='Tienda destino', on_delete=django.db.models.deletion.PROTECT, related_name='planificaciones_destino', to='main.sucursal'),
        ),
        migrations.AlterField(
            model_name='salidanormalizada',
            name='cedis_origen',
            field=models.ForeignKey(blank=True, help_text='Almacén origen (si aplica)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salidas_origen', to='main.cendis'),
        ),
        migrations.AlterField(
            model_name='salidanormalizada',
            name='sucursal_destino',
            field=models.ForeignKey(blank=True, help_text='Tienda destino', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salidas_destino', to='main.sucursal'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='bpl_id',
            field=models.IntegerField(help_text='ID único de la sucursal en el sistema ERP', unique=True),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='name',
            field=models.CharField(help_text='Nombre de la tienda/sucursal', max_length=255, unique=True),
        ),
    ]
