# Generated by Django 6.0.1 on 2026-01-16 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_sucursal_options_alter_cendis_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pvp',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pvps', to='main.product'),
        ),
    ]
