# Generated by Django 6.0.1 on 2026-01-16 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_pvp_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapeoCedis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_crudo', models.CharField(help_text='Nombre tal como aparece en los Excel', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cedis_oficial', models.ForeignKey(help_text='CEDIS oficial al que corresponde', on_delete=django.db.models.deletion.CASCADE, related_name='mapeos', to='main.cendis')),
            ],
            options={
                'verbose_name': 'Mapeo de CEDIS',
                'verbose_name_plural': 'Mapeos de CEDIS',
                'ordering': ['nombre_crudo'],
            },
        ),
        migrations.CreateModel(
            name='MapeoSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_crudo', models.CharField(help_text='Nombre tal como aparece en los Excel', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sucursal_oficial', models.ForeignKey(help_text='Sucursal oficial a la que corresponde', on_delete=django.db.models.deletion.CASCADE, related_name='mapeos', to='main.sucursal')),
            ],
            options={
                'verbose_name': 'Mapeo de Sucursal',
                'verbose_name_plural': 'Mapeos de Sucursales',
                'ordering': ['nombre_crudo'],
            },
        ),
    ]
