# Generated by Django 6.0.1 on 2026-01-28 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_mapeos'),
    ]

    operations = [
        migrations.CreateModel(
            name='GerenteRegional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del gerente regional', max_length=255, unique=True)),
                ('email', models.EmailField(blank=True, help_text='Correo electrónico del gerente', max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, help_text='Teléfono de contacto', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gerente Regional',
                'verbose_name_plural': 'Gerentes Regionales',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='mapeocedis',
            name='nombre_crudo',
            field=models.CharField(help_text='Nombre o ID tal como aparece en los Excel', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='mapeosucursal',
            name='nombre_crudo',
            field=models.CharField(help_text='Nombre o ID tal como aparece en los Excel', max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la región', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gerente', models.ForeignKey(blank=True, help_text='Gerente responsable de esta región', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regiones', to='main.gerenteregional')),
            ],
            options={
                'verbose_name': 'Región',
                'verbose_name_plural': 'Regiones',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='sucursal',
            name='region',
            field=models.ForeignKey(blank=True, help_text='Región a la que pertenece esta sucursal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sucursales', to='main.region'),
        ),
    ]
