# Generated by Django 6.0.1 on 2026-01-28 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_gerenteregional_alter_mapeocedis_nombre_crudo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='gerente',
            field=models.ForeignKey(blank=True, help_text='Gerente Regional responsable de esta sucursal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sucursales', to='main.gerenteregional'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='region',
            field=models.ForeignKey(blank=True, help_text='Región geográfica a la que pertenece esta sucursal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sucursales', to='main.region'),
        ),
    ]
