# Generated by Django 6.0.1 on 2026-01-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_sucursal_gerente_alter_sucursal_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='IgnorarCedis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_crudo', models.CharField(help_text='Nombre de CEDIS tal como aparece en los Excel que debe ser ignorado', max_length=255, unique=True)),
                ('razon', models.CharField(blank=True, default='', help_text='Razón por la cual se ignora este CEDIS', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'CEDIS Ignorado',
                'verbose_name_plural': 'CEDIS Ignorados',
                'ordering': ['nombre_crudo'],
            },
        ),
        migrations.CreateModel(
            name='IgnorarSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_crudo', models.CharField(help_text='Nombre de Sucursal tal como aparece en los Excel que debe ser ignorado', max_length=255, unique=True)),
                ('razon', models.CharField(blank=True, default='', help_text='Razón por la cual se ignora esta Sucursal', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sucursal Ignorada',
                'verbose_name_plural': 'Sucursales Ignoradas',
                'ordering': ['nombre_crudo'],
            },
        ),
        migrations.AlterField(
            model_name='salida',
            name='normalize_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('ok', 'Normalizado'), ('error', 'Error'), ('ignored', 'Ignorado')], default='pending', max_length=20),
        ),
    ]
